[package]
name = "cabbage"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
redis-protocol = "6.0.0"
simplelog = { workspace = true }
tokio = { workspace = true }
